119 Authentication failure messages
LujainKhalaf/SOEN341 pull request #122
Opened 2021-02-16 01:31 UTC by fadi-albasha

- Added a message to show sign in failure when the password is incorrect.
- Made the message shown when email is not signed up similar to the message when the password is incorrect.

close #119

2021-02-16 02:01 UTC, jason-gerard reviewed
Other than that looks good

2021-02-16 02:01 UTC, jason-gerard commented on app/controllers/user_controller.py
> +        return '', 200
This should be 204, success with no response payload

2021-02-16 02:12 UTC, fadi-albasha commented on app/controllers/user_controller.py
> +        return '', 200
I know, I tried to change it to 204 in this commit but it resulted in a conflict. I'll fix it later.

2021-02-16 02:15 UTC, fadi-albasha commented on app/controllers/user_controller.py
> +        return '', 200
It's fixed now.

2021-02-16 02:16 UTC, jason-gerard approved these changes, later dismissed
Fixed the conflict, when that happens its because your branch is behind main just have to rebase

2021-02-16 06:09 UTC, mnashat approved these changes, later dismissed

2021-02-16 14:35 UTC, LujainKhalaf requested changes
Since this is a sign in page, I believe the best error message would be: Incorrect username and/OR password.
Having all of them is too excessive for an error message, and since it's just a sign-in page, the length of the password required was demanded during the the sign up, so that can be excluded from error sign in, same thing for the valid email.

2021-02-17 00:13 UTC, fadi-albasha commented
I agree with @LujainKhalaf, I'll remove validation error messages form the sign in page.

2021-02-17 00:34 UTC, fadi-albasha commented
I removed validation error messages in the sign in page.

2021-02-17 00:50 UTC, mnashat approved these changes

2021-02-18 05:38 UTC, LujainKhalaf approved these changes
Great work!

2021-02-18 05:38 UTC, merged