112_113 modal followers following user list preview
LujainKhalaf/SOEN341 pull request #163
Opened 2021-03-25 02:27 UTC by LujainKhalaf

Created modal to preview user's following and follower list

2021-03-25 03:01 UTC, domsec requested changes
These are the issues I've noticed at a quick glance. I also did not see a follow button in the modal for people you aren't following as shown the User Interface section of #112 .

2021-03-25 03:01 UTC, domsec commented on app/static/style.css
> +#modal-following{
Add a fixed height, center the modal and title.

2021-03-25 03:01 UTC, domsec commented on app/templates/account/profile/_profile-info.html
> +                    <button type="button" style="border: none; background-color: transparent;"
No need to make this a button. Just add the custom attributes to the original <a> tag

2021-03-25 03:01 UTC, domsec commented on app/templates/account/profile/_profile-info.html
> +                    <button type="button" style="border: none; background-color: transparent;"
Same as above

2021-03-25 03:01 UTC, domsec commented on app/templates/components/follow_button.html
> +                var listitem =
Generate the template as a return inside `user_controller.get_following()` and `user_controller.get_followers()` similar to how we populate the comments inside the image modal.

2021-03-25 03:01 UTC, domsec commented on app/templates/components/follow_button.html
> +            onclick="follow(this)" this-user-id="{{ user.user_id }}" me-username="{{ me.username }}" me-full-name="{{ me.full_name }}" me-id="{{ me.user_id }}">
Not needed with below comment.

2021-03-25 03:01 UTC, domsec commented on app/templates/components/followers_following_modal.html
> +                                <div class="post-comment-text">
`post-comment-text` is unrelated to with following/follower. Use appropriate naming for the context.

2021-03-25 03:01 UTC, domsec commented on app/templates/components/followers_following_modal.html
> +                            <br>
Should be handled with CSS

2021-03-25 03:01 UTC, domsec commented on app/templates/components/followers_following_modal.html
> +        <!-- -->
Remove

2021-03-25 03:01 UTC, domsec commented on app/templates/components/followers_following_modal.html
> +                                            class="post-comment-profile-pic rounded-circle"></a>
Use appropriate naming for the context. Style username and full name similar to the sidebar but using the post comment modal profile pic CSS.

2021-03-25 03:04 UTC, LujainKhalaf commented on app/templates/account/profile/_profile-info.html
> +                    <button type="button" style="border: none; background-color: transparent;"
@mnashat and I attempted to do that, but since bootstrap uses it as a button, it wouldn't work with the original tag

2021-03-26 01:52 UTC, jason-gerard commented on app/templates/components/follow_button.html
> +                var listitem =
done

2021-03-26 02:53 UTC, mnashat approved these changes, later dismissed
Great work!

2021-03-26 16:43 UTC, jason-gerard approved these changes, later dismissed

2021-03-28 01:29 UTC, domsec commented
- Fixed styling to match rest of the site
- Disable/Enable the clickability of both the `followers` and `following` to display their respective modals based on their respective counts
    - If count = 0, don't allow the modal to display
    - If count > 0, allow the ability to display the modal

2021-03-28 01:36 UTC, domsec commented
Added the issue # for all commits that lacked them in the commit message as requested by the TAs

2021-03-28 02:40 UTC, jason-gerard approved these changes
nice

2021-03-28 02:43 UTC, mnashat approved these changes

2021-03-28 14:51 UTC, domsec approved these changes

2021-03-28 14:51 UTC, merged